spring:
 datasource:
  url: jdbc:mysql://localhost:3308/gestionstock?createDatabaseIfNotExist=true
  username: root
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver

##Security DBMS
 jpa:
  database: MYSQL
  show-sql: false
  hibernate:
   ddl-auto: update
  properties:
   hibernate: 
    dialect: org.hibernate.dialect.MySQLDialect
server:
 port: 8881
  
